#!/bin/bash
# depends on pandoc & md2gemini
for filename in content/**/*.md
do
	# build html
	pandoc "${filename}" -o "${filename/\.md/\.html}" \
	--standalone \
	--metadata-file=pandoc/metadata.yaml \
	--template=pandoc/template.html \
	--reference-links --reference-location=block \
	--lua-filter pandoc/links-to-html.lua
	
	# build gemtext 
	md2gemini --md-links "${filename}" > "${filename/\.md/\.gmi}"
done
